build:
  stage: build
  interruptible: true
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  variables:
    FQ_IMAGE_NAME: "$CI_REGISTRY_IMAGE:builder-$CI_COMMIT_SHA"
  script:
    - /kaniko/executor
      --build-arg TARGETARCH=amd64
      --cache=true
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/build.Dockerfile"
      --destination "$FQ_IMAGE_NAME"
      --use-new-run
      --no-push
      --target cached-builder
    - /kaniko/executor
      --build-arg TARGETARCH=amd64
      --build-arg CI_API_V4_URL=$CI_API_V4_URL
      --build-arg CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH
      --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA
      --build-arg CI_COMMIT_TAG=$CI_COMMIT_TAG
      --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN
      --build-arg CI_PROJECT_DIR=$CI_PROJECT_DIR
      --build-arg CI_PROJECT_ID=$CI_PROJECT_ID
      --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE
      --build-arg CI_REPOSITORY_URL=$CI_REPOSITORY_URL
      --cache=false
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/build.Dockerfile"
      --use-new-run
      --no-push

build-mac:
  stage: build
  interruptible: true
  image: ghcr.io/cirruslabs/macos-runner:sonoma
  tags:
    - tart-installed

  script:
    - git fetch --unshallow || echo 'already unshallow'
    - brew install go && go version
    - make ci-macos -j16

release:
  stage: build
  interruptible: true
  image: "$CI_REGISTRY_IMAGE:builder-$CI_COMMIT_SHA"
  needs:
    - build-mac
    - build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - make ci-release
