include: ".ci/dockerfile-hash.yaml"

# builder:
#   stage: build
#   interruptible: true
#   image:
#     name: gcr.io/kaniko-project/executor:v1.14.0-debug
#     entrypoint: [""]
#   variables:
#     FQ_IMAGE_NAME: "$CI_REGISTRY_IMAGE:builder-$DOCKERFILE_HASH"
#   script:
#     - /kaniko/executor
#       --build-arg TARGETARCH=amd64
#       --build-arg DOCKERFILE_HASH=$DOCKERFILE_HASH
#       --cache=true
#       --context "${CI_PROJECT_DIR}"
#       --dockerfile "${CI_PROJECT_DIR}/docker/build.Dockerfile"
#       --destination "$FQ_IMAGE_NAME"

# build:
#   stage: build
#   interruptible: true
#   image: "$CI_REGISTRY_IMAGE:builder-$DOCKERFILE_HASH"
#   script:
#     - git fetch --unshallow || echo 'already unshallow'
#     - make ci -j$(nproc)
#   artifacts:
#     reports:
#       dotenv: .ci/build.env

# build-docker-amd64:
#   stage: build
#   interruptible: true
#   needs:
#     - job: build
#       artifacts: true
#   image:
#     name: gcr.io/kaniko-project/executor:v1.14.0-debug
#     entrypoint: [""]
#   script:
#     - /kaniko/executor
#       --build-arg TARGETARCH=amd64
#       --build-arg AQUAREUM_URL=$AQUAREUM_URL_AMD64
#       --context "${CI_PROJECT_DIR}"
#       --dockerfile "${CI_PROJECT_DIR}/docker/release.Dockerfile"
#       --destination "$CI_REGISTRY_IMAGE:$AQUAREUM_BRANCH-amd64"
#       --destination "$CI_REGISTRY_IMAGE:$AQUAREUM_VERSION-amd64"

build-docker-arm64:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: build
  interruptible: true
  # needs:
  #   - job: build
  #     artifacts: true
  image:
    name: gcr.io/kaniko-project/executor@sha256:ab3929075d3b53d9959c15e8ddc212c1d7165ee02eb8b3abfb684256bce53551
    entrypoint: [""]
  script:
    - /kaniko/executor
      --build-arg TARGETARCH=arm64
      --build-arg AQUAREUM_URL=https://git.aquareum.tv/aquareum-tv/aquareum/-/package_files/857/download
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/release.Dockerfile"
      --no-push
      # --destination "$CI_REGISTRY_IMAGE:$AQUAREUM_BRANCH-arm64"
      # --destination "$CI_REGISTRY_IMAGE:$AQUAREUM_VERSION-arm64"
# build-android:
#   stage: build
#   interruptible: true
#   image: "$CI_REGISTRY_IMAGE:builder-$DOCKERFILE_HASH"
#   script:
#     - git fetch --unshallow || echo 'already unshallow'
#     - make ci-android -j$(nproc)

# build-mac:
#   stage: build
#   interruptible: true
#   image: ghcr.io/cirruslabs/macos-runner:sonoma
#   tags:
#     - tart-installed

#   script:
#     - git fetch --unshallow || echo 'already unshallow'
#     - brew install go && go version
#     - make ci-macos -j16

# release:
#   stage: build
#   interruptible: true
#   image: "$CI_REGISTRY_IMAGE:builder-$DOCKERFILE_HASH"
#   needs:
#     - build-mac
#     - build-android
#     - build-docker-amd64
#     - build-docker-arm64
#     - build
#   rules:
#     - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
#   script:
#     - make ci-release
