builder:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  variables:
    FQ_IMAGE_NAME: "$CI_REGISTRY_IMAGE:builder-$CI_COMMIT_SHA"
  script:
    - /kaniko/executor
      --build-arg TARGETARCH=amd64
      --cache=true
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/build.Dockerfile"
      --destination "$FQ_IMAGE_NAME"

build:
  stage: build
  needs:
    - builder
  image: "$CI_REGISTRY_IMAGE:builder-$CI_COMMIT_SHA"
  script:
    - git fetch --unshallow || echo 'already unshallow'
    - make ci

build-mac:
  stage: build
  image: ghcr.io/cirruslabs/macos-runner:sonoma
  tags:
    - tart-installed

  script:
    - git fetch --unshallow || echo 'already unshallow'
    - brew install go && go version
    - make ci-macos

release:
  stage: build
  image: "$CI_REGISTRY_IMAGE:builder-$CI_COMMIT_SHA"
  needs:
    - build-mac
    - build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - make ci-release
