variables:
  GIT_DEPTH: 9999999999999

build:
  stage: build
  interruptible: true
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - ./util/kaniko-ci.sh build

build-mac:
  stage: build
  interruptible: true
  image: ghcr.io/cirruslabs/macos-runner:sonoma
  tags:
    - tart-installed

  script:
    - git fetch --unshallow || echo 'already unshallow'
    - brew install go && go version
    - make ci-macos -j16

release:
  stage: build
  interruptible: true
  image: "$CI_REGISTRY_IMAGE:builder-$CI_COMMIT_SHA"
  needs:
    - build-mac
    - build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - make ci-release
