include: ".ci/dockerfile-hash.yaml"

builder:
  stage: build
  interruptible: true
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  variables:
    FQ_IMAGE_NAME: "$CI_REGISTRY_IMAGE:builder-$DOCKERFILE_HASH"
  script:
    - /kaniko/executor
      --build-arg TARGETARCH=amd64
      --build-arg DOCKERFILE_HASH=$DOCKERFILE_HASH
      --cache=true
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/build.Dockerfile"
      --destination "$FQ_IMAGE_NAME"

build:
  stage: build
  interruptible: true
  image: "$CI_REGISTRY_IMAGE:builder-$DOCKERFILE_HASH"
  script:
    - git fetch --unshallow || echo 'already unshallow'
    - make ci -j$(nproc)

build-android:
  stage: build
  interruptible: true
  image: "$CI_REGISTRY_IMAGE:builder-$DOCKERFILE_HASH"
  script:
    - git fetch --unshallow || echo 'already unshallow'
    - make ci-android -j$(nproc)

build-mac:
  stage: build
  interruptible: true
  image: ghcr.io/cirruslabs/macos-runner:sonoma
  tags:
    - tart-installed

  script:
    - git fetch --unshallow || echo 'already unshallow'
    - brew install go && go version
    - make ci-macos -j16

release:
  stage: build
  interruptible: true
  image: "$CI_REGISTRY_IMAGE:builder-$DOCKERFILE_HASH"
  needs:
    - build-mac
    - build-android
    - build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - make ci-release
